### ISSUE TITLE
list.astype(np.float32) cause err

### ISSUE THREAD

**Issue by 98729** [ChenDRAG/CEP-energy-guided-diffusion#2]
When running train_critic.py after training behavior model, line 106 raises an error because list doesn't have astype method. How to fix this?

**Comment by ChenDRAG** [comment]
I've made a PR 4cc0622fbe6a032df3e2fd661c5adcdc69cf4b0f trying to fix this issue. So sorry for the inconvenience.

The issue will be closed for now. Feel free to reopen it if there's a further problem.
