### ISSUE TITLE
usage of fake_actions and fake_next_actions

### ISSUE THREAD

**Issue by 98729** [ChenDRAG/CEP-energy-guided-diffusion#3]
I am confused about fake_actions and fake_next_actions. Why do you use fake_actions and fake_next_actions in train_critic? Why their sizes are different from dataset.actions?

**Comment by ChenDRAG** [comment]
fake_actions and fake_next_actions are support action set generated by the diffusion behavior model. They are used to train the Q-network. Please refer to section 5.3 in the paper for details.

It's also possible to use the technique of implicit Q-learning to replace the current Q-learning method to avoid fake_actions and fake_next_actions when training critics.
