### ISSUE TITLE
Q-network loss not converging

### ISSUE THREAD

**Issue by atagle123** [ChenDRAG/CEP-energy-guided-diffusion#5]
Hi, great work! 
I am currently trying to replicate the code, but I am experiencing an issue with the loss of my Q-network. Specifically, the loss oscillates between the range of 0.5 and 1.5 and doesn't seem to converge.

Is this behavior expected, or could there be an issue with my implementation? Any guidance you can provide would be greatly appreciated. 
Thank you!

**Comment by ChenDRAG** [comment]
The Q loss is basically a bootstrapping loss so it is normal to be unstable. I would recommend directly checking the environment evaluation rewards to see if the code is okay. 
If you still have problems, please give me more implementation details and experimental results.

**Comment by atagle123** [comment]
Thank you for your response!  I will check the evaluation and the implementation.
